/* Patches */
#include "alpha.c"
#include "alternativetags.c"
#include "autostart.c"
#include "cyclelayouts.c"
#include "fullscreen.c"
#include "movestack.c"
#include "scratchpad.c"
#include "shiftview.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "xrdb.c"
/* Layouts */
#include "layout_facts.c"
#include "fibonacci.c"
#include "monocle.c"
#include "tile.c"
